### Problem 2 - Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def compute_sum():
    sum = 0
    #base case
    x = 1 # current fibonacci term
    y = 2 # next fibonacci term
    while x <= 4000000:
        if x % 2 == 0:
            sum += x
        x, y = y, y + x    #x will assume y, y will assume (old y + old x)
    return sum

if __name__ == "__main__":
	print(compute_sum())
